### ISSUE TITLE
AttributeError: 'module' object has no attribute 'loads'

### ISSUE THREAD

**Issue by fluancefg** [dalibo/powa#45]
Hi,
I've tried the new powa-web version 2.0.5, but I'm unfortunate because now I get the following error when I try to run ./powa-web:

Traceback (most recent call last):
  File "./powa-web", line 2, in <module>
    from powa import make_app
  File "/home/pi/powa-web-2.0.5/powa/__init__.py", line 17, in <module>
    from powa.overview import Overview
  File "/home/pi/powa-web-2.0.5/powa/overview.py", line 5, in <module>
    from powa.dashboards import (
  File "/home/pi/powa-web-2.0.5/powa/dashboards.py", line 10, in <module>
    from powa.compat import with_metaclass, classproperty, hybridmethod
  File "/home/pi/powa-web-2.0.5/powa/compat.py", line 17, in <module>
    (JSON_OID,), "JSON", json.loads)
AttributeError: 'module' object has no attribute 'loads'

**Comment by rdunklau** [comment]
My bad, thank your for your patience.

This bug only occurs using python2 (relative imports).
This should be fixed in the latest release.

Getting some (basic) automated tests running on python 2.6, 2.7 and 3.4 as well as some combination of various psycopg2 / tornado / sqlalchemy version should prevent that.

**Comment by fluancefg** [comment]
I've downloaded the latest version (2.0.6) and it works well.

Thank you
